default_agent: update_checker2
agents:
  update_checker:
    name: update_checker
    entrypoint: /Users/minorun365/git/minorun365/amplify-agentcore-sample/agent/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/minorun365/git/minorun365/amplify-agentcore-sample/agent
    aws:
      execution_role: arn:aws:iam::282048599344:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-2f5856a957
      execution_role_auto_create: false
      account: '282048599344'
      region: ap-northeast-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-282048599344-ap-northeast-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: update_checker_mem-d0P0435Be5
      memory_arn: arn:aws:bedrock-agentcore:ap-northeast-1:282048599344:memory/update_checker_mem-d0P0435Be5
      memory_name: update_checker_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  update_checker2:
    name: update_checker2
    entrypoint: /Users/minorun365/git/minorun365/amplify-agentcore-sample/agent/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/minorun365/git/minorun365/amplify-agentcore-sample/agent
    aws:
      execution_role: arn:aws:iam::282048599344:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-22ff0b072e
      execution_role_auto_create: false
      account: '282048599344'
      region: ap-northeast-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-282048599344-ap-northeast-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: update_checker2-tk0kzH5wCo
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:282048599344:runtime/update_checker2-tk0kzH5wCo
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
